### PR TITLE
Match regex

### PR DESCRIPTION
**Pull request by poornima-krishnasamy**
Related to:https://github.com/ministryofjustice/cloud-platform/issues/1332
Rewrote to match certain patterns instead of matching specific keywords.

### CODE REVIEW

**Review by digitalronin — APPROVED** [review]
I would add .built-docker-image to .gitignore

**Comment by poornima-krishnasamy** [comment]
> I would add .built-docker-image to .gitignore

@digitalronin, can u please check. Also, update the secret to have MOJ token.

**Comment by digitalronin** [comment]
This looks good, @poornima-moj 

If this is going to run in the cluster, maybe it would be better to get the token from the kubernetes secret? That way, if we ever need to rotate it, we only need to do it in one place.

**Comment by poornima-krishnasamy** [comment]
> This looks good, @poornima-moj
> 
> If this is going to run in the cluster, maybe it would be better to get the token from the kubernetes secret? That way, if we ever need to rotate it, we only need to do it in one place.

Thanks @digitalronin . Yes, the token is in the secrets.yaml file which will be deployed as kubernetes secret and passed as env vars.

**Comment by digitalronin** [comment]
What I mean is, the token is already present in the concourse-main namespace. Will this app. run with enough permissions to read it from there? If so, we wouldn't need to duplicate the token here, would we?

**Comment by poornima-krishnasamy** [comment]
> What I mean is, the token is already present in the concourse-main namespace. Will this app. run with enough permissions to read it from there? If so, we wouldn't need to duplicate the token here, would we?

Good thought @digitalronin. In that case,  let me follow the gitops path and see whether that can be part of the pipeline. Not sure to give the namespace/app special permissions to get things from concourse-main just because Cloud Platform build it.

**Comment by poornima-krishnasamy** [comment]
> > What I mean is, the token is already present in the concourse-main namespace. Will this app. run with enough permissions to read it from there? If so, we wouldn't need to duplicate the token here, would we?
> 
> Good thought @digitalronin. In that case, let me follow the gitops path and see whether that can be part of the pipeline. Not sure to give the namespace/app special permissions to get things from concourse-main just because Cloud Platform build it.

Also, this token is specific to the Answerbot App so not sure this is in concourse-main.

**Review by digitalronin — APPROVED** [review]

**Pull request merged**
